services:
  api:
    build: ./docker/backend
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./api:/app
      - ./filestore:/app/filestore
      - ./prompts:/app/prompts
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      - /app/.next
    env_file:
      - .env
    depends_on:
      - api
    command: npm run dev

  init:
    build: ./docker/backend
    volumes:
      - ./api:/app
      - ./fixtures:/app/fixtures
      - ./init.py:/app/init.py:ro
    env_file:
      - .env
    command: python /app/init.py
    depends_on:
      - api
      - db
 
  jupyter:
    build: ./docker/backend
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./nb:/home/jovyan/nb
      - ./api:/home/jovyan/api
      - ./filestore:/home/jovyan/api/filestore
      - ./prompts:/home/jovyan/api/prompts
    env_file:
      - .env
    command: jupyter lab --ip 0.0.0.0 --port 8888 --NotebookApp.token='' --NotebookApp.password=''
     
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  worker:
    build: ./docker/backend
    working_dir: /app
    volumes:
      - ./api:/app
      - ./filestore:/app/filestore
    env_file:
      - .env
    command: rq worker --url redis://redis:6379 --logging_level WARNING
    depends_on:
      - redis
      - db

  monitor:
    build: ./docker/backend
    ports:
      - "9181:9181"
    env_file:
      - .env
    command: rq-dashboard --redis-url redis://redis:6379 --port 9181 --bind 0.0.0.0
    depends_on:
      - redis

volumes:
  mongo_data: