# docker-compose.yml

services:
  jupyter:
    build: ./docker
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./nb:/home/jovyan/nb
    environment:
      - JUPYTER_ENABLE_LAB=yes
    env_file:
      - .env
    command: jupyter lab --ip 0.0.0.0 --port 8888 --NotebookApp.token='' --NotebookApp.password=''
  api:
    build: ./docker
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./api:/app
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build: ./docker
    ports:
      - "80:80"
    working_dir: /app
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    command: streamlit run Home.py --server.port 80 --server.address 0.0.0.0
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
